version: '3'
services:
  proxy:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 8080:80
    environment:
      - PORT=80
      # `localhost2,localhost3` is for testing/illustration purposes to show how
      # HAProxy can detect multiple root domains.
      - ALLOWED_HOSTS=localhost,localhost2,localhost3
      - MAIN_PORT=80
      - TUNNELTO_CTRL_PORT=5000
      - TUNNELTO_TUNNEL_PORT=5001
